### ISSUE TITLE
TypeError in socket.bind

### ISSUE THREAD

**Issue by JavierNR** [sfera-labs/exo-sense-py-modbus#1]
Hello! 
First, many thanks for tweaking original pycom lib, and share on github.

I'm using the library successfully with WiPy devices as Modbus TCP server, but there's some problem I can't find under another ESP32 board (olimex ESP32-POE) with micropython v1.11.
The exact same code works without problems under WiPy, but on micropython throws this error:
```
Traceback (most recent call last):
  File "main.py", line 47, in <module>
  File "modbus.py", line 44, in bind
  File "/lib/uModBus/tcp.py", line 144, in bind
TypeError: function takes 2 positional arguments but 1 were given
```
I've added a print over line 144:
`self._sock.bind((socket.getaddrinfo(local_ip, local_port))[0][-1])`
In order to see if local_ip and local_port have correct values and also checked socket.getaddrifo() returns the same tuple both with WiPy and Micropython.

At the moment I'm trying, but I'm not obtaining good results. Perhaps newer usocket library breaks something?

Best regards

**Comment by JavierNR** [comment]
Closing this issue, because I've opened in wrong repository.
The correct one: [https://github.com/sfera-labs/pycom-modbus/issues/2](url)
